CREATE TABLE IF NOT EXISTS user_login_info (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  first_ip TEXT NOT NULL,
  first_login_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_ip TEXT NOT NULL,
  last_login_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_agent TEXT NOT NULL
);
